#!/usr/bin/env bash
#   See README.md for details.
set -Eeuo pipefail
trap 'ec=$?; echo 1>&2 "ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
    exit $ec;' ERR

####################################################################

#   Our "test" is just to list the packages in the virtualenv.
#   (The leading spaces just make it easier to see the section separators.)
piplist() {
    local pkgdir="$1"; shift
    "$pkgdir"/.build/virtualenv/bin/pip list | sed 's/^/    /'
}


####################################################################

export PROJDIR=$(command cd $(dirname "$0") && pwd -P)

#   Simple hack to have initial -c option rebuild virtualenv.
[[ $# -gt 0 && $1 = '-c' ]] && {
    shift
    echo '────── Cleaning'
    rm -rf "$PROJDIR"/.build/virtualenv/ \
           "$PROJDIR"/packages/*/.build/virtualenv/
}

echo '━━━━━ Top-level virtual environment'
source "$PROJDIR"/pactivate -q
piplist "$PROJDIR"
deactivate

echo '━━━━━ project/* virtual environments'
for pkgdir in $PROJDIR/packages/*/requirements.txt; do
    pkgdir="$(dirname "$pkgdir")"
    echo "─────  ${pkgdir#$PROJDIR/}"
    source "$PROJDIR"/pactivate -B "$pkgdir" -q
    piplist "$pkgdir"
    deactivate
done


echo "OK"
